name: accumulate_api6
description: Dart client for Accumulate blockchain, defines basic models and API calls to work with network, supports all types of accounts.
repository: https://github.com/kompendium-ano/accumulate-dart-client
version: 0.2.9

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  bip39: ^1.0.3
  ed25519_edwards: ^0.3.1
  hex: ^0.2.0
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
